spring:
  application:
    name: eureka-ribbon-client
server:
  port: 8764
eureka:
  instance:
    appname: eureka-ribbon-client
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/