spring:
  application:
    name: eureka-feign-client
server:
  port: 8765
eureka:
  instance:
    appname: eureka-feign-client
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true