spring:
  application:
    name: service-turbine
server:
  port: 8770
turbine:
  aggregator:
    clusterConfig: default
  appConfig: eureka-ribbon-client,eureka-feign-client
  clusterNameExpression: new String("default")
eureka:
  instance:
  appname: service-turbine
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/